#!/bin/bash
# Script to extract ImageID from cargo risczero build output
# This should be run after 'cargo risczero build' or piped from its output

# Get the script directory and ensure we're in risc0-guest directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR" || exit 1

# Create elf directory if it doesn't exist
mkdir -p elf

OUTPUT_FILE="elf/image_id.rs"

# Extract ImageID from stdin or from the last build
if [ -t 0 ]; then
    # No stdin, try to get from last build output
    echo "Reading from last cargo risczero build output..."
    # You can pipe: cargo risczero build 2>&1 | ./gen_image_id_from_build.sh
    echo "Error: No input. Pipe cargo risczero build output to this script, or run:"
    echo "  cargo risczero build 2>&1 | ./gen_image_id_from_build.sh"
    exit 1
fi

# Read from stdin and extract ImageID
IMAGE_ID=$(grep -oP 'ImageID: \K[a-f0-9]{64}' | head -1)

if [ -z "$IMAGE_ID" ]; then
    echo "Error: Could not extract ImageID from build output" >&2
    exit 1
fi

# Convert hex string to byte array format for Rust
BYTES_ARRAY=""
for i in $(seq 0 2 62); do
    BYTE="${IMAGE_ID:$i:2}"
    BYTES_ARRAY="${BYTES_ARRAY}0x${BYTE}, "
done
BYTES_ARRAY="${BYTES_ARRAY%, }"  # Remove trailing comma and space

# Generate the Rust file
cat > "$OUTPUT_FILE" << EOF
// Auto-generated file - do not edit manually
// ImageID: $IMAGE_ID
// Generated by gen_image_id_from_build.sh

pub const IMAGE_ID_HEX: &str = "$IMAGE_ID";

pub const IMAGE_ID_BYTES: [u8; 32] = [$BYTES_ARRAY];
EOF

echo "Generated $OUTPUT_FILE with ImageID: $IMAGE_ID" >&2

